### ISSUE TITLE
`emd foo.dck` should run the file

### ISSUE THREAD

**Issue by athas** [vmchale/dickinson#1]
This is enough to make `#!/usr/bin/env emd` work, since `emd` seems to ignore everything prior to the first `%-`.

**Comment by athas** [comment]
Oh, I'm wrong about `emd` ignoring stuff.  Still, it would be nice if shebangs could work!

**Comment by athas** [comment]
For now, I used this wrapper script `emdrun`:

```
#!/usr/bin/env bash

emd run <(cat "$1" | awk '/%-/ { prog = 1; } { if (prog) print; }')
```

**Comment by vmchale** [comment]
Oh, that would be a nice feature! I'll have to look at how to do this with `optparse-applicative` :)

**Comment by vmchale** [comment]
Ah, okay, figured it out... (`<|>`)

**Comment by vmchale** [comment]
Hm, I suppose the `#!/usr/bin/env emd` is still a problem...

**Comment by athas** [comment]
You could always provide a separate `runemd` executable.

**Comment by vmchale** [comment]
Ah that's true! For now I suppose it's easier to change the lexer; plus less space :)
